[project]
name = "gidrator-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.16.1",
    "asyncpg>=0.30.0",
    "fastapi>=0.115.12",
    "greenlet>=3.2.2",
    "pydantic-settings>=2.9.1",
    "pytz>=2025.2",
    "sqlalchemy>=2.0.41",
    "uvicorn>=0.34.2",
]

[project.optional-dependencies]
dev = [
  "black",
  "flake8",
  "isort",
  "mypy",
  "pytest",
  "pytest-asyncio",
]

[tool.setuptools]
packages = ["app", "scripts"]

[project.scripts]
check = "scripts.commands:check"
dev = "scripts.commands:dev"
format = "scripts.commands:format"
lint = "scripts.commands:lint"
migrate = "scripts.commands:migrate"
prod = "scripts.commands:prod"
serve = "scripts.commands:serve"
start = "scripts.commands:start_all"
test = "scripts.commands:test"


[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
asyncio_mode = "strict"
filterwarnings = [
  "ignore::pydantic.PydanticDeprecatedSince20",
]
markers = [
  "integration: marks tests as integration tests",
]

[tool.mypy]
plugins = ["sqlalchemy.ext.mypy.plugin"]

[[tool.mypy.overrides]]
ignore_errors = true
module = "app.core.migrations.*"

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61.0"]

[tool.pylint.messages_control]
disable = [
  "unsubscriptable-object",
  "not-callable",
]