[project]
dependencies = [
  "aio-pika>=9.5.5",
  "aioboto3==13.1",
  "alembic>=1.16.1",
  "argon2-cffi>=23.1.0",
  "asyncpg>=0.30.0",
  "autoflake>=2.3.1",
  "fastapi>=0.115.12",
  "faststream[cli,rabbit]>=0.5.42",
  "greenlet>=3.2.2",
  "itsdangerous>=2.2.0",
  "jinja2>=3.1.6",
  "passlib>=1.7.4",
  "pre-commit>=4.2.0",
  "pydantic-settings>=2.9.1",
  "pydantic[email]>=2.11.5",
  "python-jose>=3.4.0",
  "python-multipart>=0.0.20",
  "pytz>=2025.2",
  "redis>=6.2.0",
  "sqlalchemy>=2.0.41",
  "starlette-admin>=0.15.1",
  "uvicorn>=0.34.2",
]
description = "Add your description here"
name = "gidrator-backend"
readme = "README.md"
requires-python = ">=3.11"
version = "0.1.0"

[project.optional-dependencies]
dev = [
  "black",
  "flake8",
  "isort",
  "mypy",
  "pytest",
  "pytest-asyncio",
]

[tool.setuptools]
packages = ["app", "scripts"]

[project.scripts]
activate = "scripts.commands:activate"
check = "scripts.commands:check"
dev = "scripts.commands:dev"
create_superuser = "scripts.commands:run_create_superuser"
format = "scripts.commands:format"
lint = "scripts.commands:lint"
migrate = "scripts.commands:migrate"
prod = "scripts.commands:prod"
serve = "scripts.commands:serve"
setup = "scripts.commands:setup"
start = "scripts.commands:start_all"
test = "scripts.commands:test"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
asyncio_mode = "strict"
filterwarnings = [
  "ignore::pydantic.PydanticDeprecatedSince20",
]
markers = [
  "integration: marks tests as integration tests",
]

[tool.mypy]
plugins = ["sqlalchemy.ext.mypy.plugin"]

[[tool.mypy.overrides]]
ignore_errors = true
module = "app.core.migrations.*"

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61.0"]

[tool.pylint.messages_control]
disable = [
  "unsubscriptable-object",
  "not-callable",
  "no-member",
]
