"""update product model

Revision ID: 1bc2215be7ef
Revises: babf8044392d
Create Date: 2025-05-29 20:22:33.522633

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1bc2215be7ef"
down_revision: Union[str, None] = "babf8044392d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.drop_table("sub_categories")
    op.drop_table("main_categories")
    op.add_column("products", sa.Column("images", sa.JSON(), nullable=True))
    op.drop_constraint(
        op.f("products_category_id_fkey"), "products", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "products", "categories", ["category_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_column("products", "image")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("image", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "products", type_="foreignkey")
    op.create_foreign_key(
        op.f("products_category_id_fkey"),
        "products",
        "sub_categories",
        ["category_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("products", "images")
    op.create_table(
        "main_categories",
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('main_categories_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="main_categories_pkey"),
        sa.UniqueConstraint(
            "title",
            name="main_categories_title_key",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "sub_categories",
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "main_category_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["main_category_id"],
            ["main_categories.id"],
            name=op.f("sub_categories_main_category_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("sub_categories_pkey")),
    )
    op.drop_table("categories")
    # ### end Alembic commands ###
