"""empty message

Revision ID: 5acc138e36db
Revises: e67d00844c00
Create Date: 2025-06-07 02:38:46.007926

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5acc138e36db"
down_revision: Union[str, None] = "e67d00844c00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categories", sa.Column("image", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("categories", "image")
    # ### end Alembic commands ###
