"""empty message

Revision ID: 9203ae879fcb
Revises:
Create Date: 2025-07-05 21:35:03.031685

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9203ae879fcb"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.drop_table("cards")
    op.add_column("products", sa.Column("brand_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "products", "brands", ["brand_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_column("products", "brand")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("brand", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "products", type_="foreignkey")
    op.drop_column("products", "brand_id")
    op.create_table(
        "cards",
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("image", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("cards_pkey")),
        sa.UniqueConstraint(
            "title",
            name=op.f("cards_title_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_table("brands")
    # ### end Alembic commands ###
