"""empty message

Revision ID: e67d00844c00
Revises: e99aaf5d0d18
Create Date: 2025-06-05 15:55:20.587071

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e67d00844c00"
down_revision: Union[str, None] = "e99aaf5d0d18"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("categories_parent_id_fkey"), "categories", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "categories", "categories", ["parent_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "categories", type_="foreignkey")
    op.create_foreign_key(
        op.f("categories_parent_id_fkey"),
        "categories",
        "categories",
        ["parent_id"],
        ["id"],
    )
    # ### end Alembic commands ###
