"""empty message

Revision ID: e99aaf5d0d18
Revises: 73ec5e4270ee
Create Date: 2025-05-31 17:39:04.903458

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "e99aaf5d0d18"
down_revision: Union[str, None] = "73ec5e4270ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
